# Generated by Django 4.2.3 on 2024-05-10 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ambulance_documents_alter_driver_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='underFleet',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='app.fleet_owner'),
        ),
    ]
