# Generated by Django 4.2.3 on 2024-05-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_individual_owner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
