# Generated by Django 4.2.3 on 2024-05-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startLongi', models.FloatField()),
                ('startLati', models.FloatField()),
                ('endLongi', models.FloatField()),
                ('endLati', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='endLati',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='endLongi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='startLati',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='startLongi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
