# Generated by Django 4.2.3 on 2024-05-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_request_order_endlati_order_endlongi_order_startlati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
