# Generated by Django 4.2.3 on 2024-05-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='lati',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='longi',
            field=models.FloatField(default=None),
        ),
    ]
