# Generated by Django 4.2.3 on 2024-05-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_ambulance_city_individual_owner_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='individual_owner',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
