# Generated by Django 4.2.3 on 2024-05-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_ambulance_city_alter_individual_owner_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='loggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
