# Generated by Django 4.2.3 on 2024-05-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_driver_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='liscance/'),
        ),
    ]
