# Generated by Django 4.2.3 on 2024-05-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_driver_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual_owner',
            name='lati',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='individual_owner',
            name='longi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.FileField(upload_to='liscance/'),
        ),
    ]
