# Generated by Django 4.2.3 on 2024-05-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_individual_owner_lati_individual_owner_longi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('longi', models.FloatField(default=0.0)),
                ('lati', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='underFleet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.fleet_owner'),
        ),
    ]
